<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>GakumasInteropGen</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
    <GakumasRoot Condition="'$(GakumasRoot)' == ''">$(GAKUMAS_ROOT)</GakumasRoot>
    <GakumasRoot Condition="'$(GakumasRoot)' == ''">E:\DMM\gakumas</GakumasRoot>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>$(GakumasRoot)\dotnet\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging">
      <HintPath>$(GakumasRoot)\dotnet\Microsoft.Extensions.Logging.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>$(GakumasRoot)\dotnet\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection">
      <HintPath>$(GakumasRoot)\dotnet\Microsoft.Extensions.DependencyInjection.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Options">
      <HintPath>$(GakumasRoot)\dotnet\Microsoft.Extensions.Options.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Primitives">
      <HintPath>$(GakumasRoot)\dotnet\Microsoft.Extensions.Primitives.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LibCpp2IL">
      <HintPath>$(GakumasRoot)\BepInEx\core\LibCpp2IL.dll</HintPath>
    </Reference>
    <Reference Include="Cpp2IL.Core">
      <HintPath>$(GakumasRoot)\BepInEx\core\Cpp2IL.Core.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Generator">
      <HintPath>$(GakumasRoot)\BepInEx\core\Il2CppInterop.Generator.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Common">
      <HintPath>$(GakumasRoot)\BepInEx\core\Il2CppInterop.Common.dll</HintPath>
    </Reference>
    <Reference Include="AsmResolver">
      <HintPath>$(GakumasRoot)\BepInEx\core\AsmResolver.dll</HintPath>
    </Reference>
    <Reference Include="AsmResolver.DotNet">
      <HintPath>$(GakumasRoot)\BepInEx\core\AsmResolver.DotNet.dll</HintPath>
    </Reference>
    <Reference Include="AsmResolver.PE">
      <HintPath>$(GakumasRoot)\BepInEx\core\AsmResolver.PE.dll</HintPath>
    </Reference>
    <Reference Include="AsmResolver.PE.File">
      <HintPath>$(GakumasRoot)\BepInEx\core\AsmResolver.PE.File.dll</HintPath>
    </Reference>
    <Reference Include="Iced">
      <HintPath>$(GakumasRoot)\BepInEx\core\Iced.dll</HintPath>
    </Reference>
    <Reference Include="StableNameDotNet">
      <HintPath>$(GakumasRoot)\BepInEx\core\StableNameDotNet.dll</HintPath>
    </Reference>
    <Reference Include="SemanticVersioning">
      <HintPath>$(GakumasRoot)\BepInEx\core\SemanticVersioning.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>$(GakumasRoot)\BepInEx\core\MonoMod.Utils.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Backports">
      <HintPath>$(GakumasRoot)\BepInEx\core\MonoMod.Backports.dll</HintPath>
    </Reference>
    <Reference Include="Disarm">
      <HintPath>$(GakumasRoot)\BepInEx\core\Disarm.dll</HintPath>
    </Reference>
    <Reference Include="Gee.External.Capstone">
      <HintPath>$(GakumasRoot)\BepInEx\core\Gee.External.Capstone.dll</HintPath>
    </Reference>
    <Reference Include="AssetRipper.CIL">
      <HintPath>$(GakumasRoot)\BepInEx\core\AssetRipper.CIL.dll</HintPath>
    </Reference>
    <Reference Include="AssetRipper.Primitives">
      <HintPath>$(GakumasRoot)\BepInEx\core\AssetRipper.Primitives.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
